services:
    postgres:
        image: 'postgres:17'
        ports:
            - '5432:5432'
        environment:
            PGPASSWORD: 'password'
            POSTGRES_DB: 'laravel'
            POSTGRES_USER: 'laravel'
            POSTGRES_PASSWORD: 'password'
        healthcheck:
            test:
                - CMD
                - pg_isready
                - '-q'
                - '-d'
                - 'laravel'
                - '-U'
                - 'laravel'
            interval: 5s
            timeout: 5s
            retries: 5
        volumes:
            - 'postgres-volume:/var/lib/postgresql/data'

volumes:
    postgres-volume:
        driver: local
